name: 'Snyk Job Summary Action'
description: 'Greet someone' # todo

inputs:
  dependencies-report-path:
    description: '' # todo
    required: false
  code-report-path:
    description: '' # todo
    required: false

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3

    - run: npm install snyk-to-html -g
      shell: bash

    - name: convert Snyk Dependencies json to html format
      run: snyk-to-html -i snyk_dependencies.json -o snyk_dependencies.html
      shell: bash

    - name: convert Snyk Code json to html format
      run: snyk-to-html -i snyk_code.json -o snyk_code.html
      shell: bash

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: snyk-details
        path: |
          snyk_dependencies.html
          snyk_code.html
        retention-days: 7
        if-no-files-found: ignore

    - run: pip install mdutils
      name: install mdutils
      shell: bash

    - name: run script
      run: scripts/display_vulnerabilities.py
      shell: python

    - run: cat vulnerabilities.md >> $GITHUB_STEP_SUMMARY
      name: Add output to Job Summary
      shell: bash
